### ISSUE TITLE
Problems on gcc-6.1 linux

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#23] opened 2016-06-26 04:50 UTC
This is just a heads-up, in a place where (I hope) google will find it.

I am seeing two specific problems on (x86_64) gcc-6.1 linux (LFS/BLFS-svn versions):
1. With the texlive 2016 _binary_ a 2D test I created last month now puts the heading line of text onto a first page, with the drawing at the same height (i.e. at the top) of the second page. With the same binary on a gcc-5.3 system it all continues to occupy one page, and also just one page on a wholly from-source 2016 build. I'll attach the old version, renamed from .tex to .txt because github won't let me attach a .tex file. 
   [triangles.txt](https://github.com/vectorgraphics/asymptote/files/333425/triangles.txt)
2. For 3D tests, at least for those using non-zero values of render and therefore requiring freeglut, both the binary and from-source versions of asy on gcc-6.1 fail to build (missing PDF when I run pdflatex after asy). The only message in the log is:   /opt/texlive/2016/texmf-dist/asymptote/three.asy: 2905.13: runtime: 

When I changed my search terms to drop gcc-6.1, google found several matches in recent years (broken glut, bad ghostscript), usually with some form of error message. So, I started adding flags to my asy invocation, and I established that adding '-V' the test now completes correctly.

My reading of the docs suggested this invokes gsview, which I do not have, but for use in TeX it is not a problem.

I also have some separate non-TeX asy tests to produce eps, png or pdf files based on the Staats tutorial. Again, the 3D versions with non-zero render values now need -V in the invocation on gcc-6.1 systems. That is double-edged : I can rotate the images (nice, very nice - I didn't know about that) but the new image is no-longer written. For my use-case (just testing things work, and mostly as part of texlive) that is not a problem.

**Comment by johncbowman** [comment] 2016-08-29 06:24
1. This a duplicate of https://github.com/vectorgraphics/asymptote/issues/24, which is now fixed both in TL2016 and git.

2. From within the renderer you can export a file with the 'e' key (see the menu for other options).
You can specify other output formats with the -f <FORMAT> command line option.
To force 2D pdf specify -f pdf -noprc.  I haven't tried compiling under gcc 6.1 yet.

**Comment by pauloney** [comment] 2016-09-20 19:00
I just installed TL2016 from TUG and the problem has NOT been solved there.

**Closed** 2017-01-25 03:30 UTC
