### ISSUE TITLE
asymptote compatibility with wayland ?

### ISSUE THREAD

**Issue by picca** [vectorgraphics/asymptote#364] opened 2023-01-25 10:21 UTC
Hello,  I am using asy in order to build the documentation of my hkl library, from the sway environment (pure wayland).

the Debian bug report I filled against asymtote is here

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025049

the test file is here

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1025049;filename=B_b3_y.asy;msg=5

to my opinion the 

the glrender call from the backtrace seems suspicious to mee

I would like your help in order to tackle this issue.

thanks for considering

**Comment by rafelamer** [comment] 2023-01-25 17:32
Hello,
I have a similar problem i I run asy under Xvfb:

As a root:
/usr/bin/Xvfb :42 -screen 0 1024x768x24 -ac +extension GLX +render -noreset

As a normal user:
export DISPLAY=:42
asy -vvvv -f pdf -render 10 3S+1D.asy

The last lines of the output are:

GLSL version 4.50
No fragment shader interlock support
    shipout3(prefix,f,preview ? nativeformat() : format,
            ^
/usr/share/asymptote/three.asy: 2896.13

Best regards,
Rafel Amer

**Comment by johncbowman** [comment] 2023-01-25 18:30
This issue sounds very much like this problem, which was solved by upgrading the NVIDIA driver. Please give that a try and let us know. (I am still using X and haven't yet tried out Wayland since it doesn't support fvwm, but I think the problem is more likely due to a bug in the graphics driver.)

https://sourceforge.net/p/asymptote/discussion/409349/thread/d535c62247/

**Comment by rafelamer** [comment] 2023-01-25 19:31
I'm running asy in a virtual server whitout any X environment, NVIDIA card and nvidia drivers. I run Fedora 37 server and the version of freeglut is 
freeglut-3.2.2-2.fc37.x86_64

Best regards,
Rafel Amer

**Comment by johncbowman** [comment] 2023-01-26 21:49
Regarding the debian report, try:
./configure --disable-gc
make clean
make CFLAGS=-g

and then see if the backtrace changes. Running under valgrind is a good way to find the first instance of a segfault, uninitialized memory, or floating point exception.

**Comment by johncbowman** [comment] 2023-01-27 05:26
_Program terminated with signal SIGFPE, Arithmetic exception._

This suggests an FPE exception in your graphics driver. You can temporarily work around this by specifying -mask on the command line. A better work around is to identify which OpenGL call is triggering the FPE. For example, the OSMesa library in Fedora 37 generates an FPE in glLinkProgram. Commit  72670f2b7e77a8d6e1b44b82f3a240f75205416b works around an FPE on that platform. Perhaps that will solve your issue too.

**Comment by johncbowman** [comment] 2023-02-09 07:08
Now that the 2.85 release is out, can we now close this issue?

**Comment by picca** [comment] 2023-02-09 07:11
I will juste wait for the Debian release of 2.85, and report back, thanks

Frederic

**Closed** 2023-02-10 18:33 UTC
