### ISSUE TITLE
Opacity is broken again.

### ISSUE THREAD

**Issue by Gregstrq** [vectorgraphics/asymptote#184] opened 2020-10-30 16:33 UTC
My .asy file uses opacity:
```
unitsize(1inch);

real l=3.0;

pen penb = blue+3bp;
pen penr = red+2bp;
pen peng = green+2bp+opacity(0.5);

draw(arc((0,0), 0.9*0.5*l, 0, 90), penr);
draw(box((0,0),(l,l)), penb);
draw(circle((0.5*l, l), 0.15*l), peng);
```
When I try to process it with `asy -nosafe -V -f pdf my_file`, I get the following error:
>Error: /undefined in .setopacityalpha
Operand stack:
   0.5
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1988   1   3   %oparray_pop   --nostringval--   1977   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:739/1123(ro)(G)--   --dict:0/20(G)--   --dict:79/200(L)--
Current allocation mode is local
Current file position is 756
GPL Ghostscript 9.53.2: Unrecoverable error, exit code 1
/usr/share/asymptote/plain_shipout.asy: 108.11: runtime: shipout failed

I found the issue #73, so I tried to use the additional key `-nosafe`, but it did not help.
I am using Asymptote version 2.64; and as you may notice, the version of GhostScript is 9.53.2.

Is there a way to work around this issue?
Help is appreciated.

**Comment by johncbowman** [comment] 2020-10-30 16:40
Duplicate of https://github.com/vectorgraphics/asymptote/issues/155.
The solution is not to use obsolete versions of Asymptote. A work around was implemented in version 2.66;
the latest version is 2.67 and the 2.68 release should happen over the next few days.

**Closed by johncbowman** 2020-10-30 16:40 UTC

**Comment by PhysMathGe** [comment] 2020-11-08 18:40
I have the exact same problem with asymptote 2.65 (and ghostscript 9.53.3; both from an up-to-date texlive installation).

**Comment by johncbowman** [comment] 2020-11-08 19:55
Those two versions are incompatible, so don't use them together. The 2.68
release of Asymptote should be available this week.
