### ISSUE TITLE
Parameters of type pair with defaults cause unexpected type errors

### ISSUE THREAD

**Issue by DanielW0108** [vectorgraphics/asymptote#381] opened 2023-06-15 15:00 UTC
Minimal example:

```
int f (pair foo=(0,0), int x) {
  return x;
}

f(1);
```

Trying to compile this gives the following error:
`cannot call
'int f(pair foo=<default>, int x)'
with parameter '(int)'`

Calling `f(x = 1)` compiles, as does swapping the order of the parameters to this:
```
int f (int x, pair foo=(0,0)) {
  return x;
}

f(1);
```

This seems to happen whenever `x` has a type that could appear inside a pair.
The same type error happens if `int` is swapped for `real`, but swapping it for `string` avoids it:
```
string f (pair foo=(0,0), string x) {
  return x;
}

f("a");
```

Casting to a non-pair-y type seems to behave differently to casting to a pair-y type:
- Calling `f((string)1)` here does compile
- Calling `f((int)1)` for the `int` versions does not compile, likewise `f((real)1)` for the `real` version

This happens on both the web version (2.86-7) and the latest version available on my repo (2.70)

**Comment by johncbowman** [comment] 2023-06-22 18:17
This is the expected behaviour of Asymptote's function signature matching algorithm, as described here:

https://asymptote.sourceforge.io/doc/Default-arguments.html

See also https://asymptote.sourceforge.io/doc/Named-arguments.html

In your example, the int argument can be cast to a pair, and so it assigned to the first argument. You then need to supply a second int since the second argument does not have a default value.

**Closed by johncbowman** 2023-06-22 18:17 UTC

**Comment by johncbowman** [comment] 2023-06-22 18:18
Perhaps what you really intended was

```
int f (explicit pair foo=(0,0), int x) {
  return x;
};
```

**Comment by DanielW0108** [comment] 2023-06-26 15:28
Ah, I wasn't aware that ints can be implicitly cast to pairs - makes sense when treating pairs as complex numbers, but unintuitive when they're mostly being used as coordinates. Thanks for the response.
