### ISSUE TITLE
Problems with 3D rendering?

### ISSUE THREAD

**Issue by natkuhn** [vectorgraphics/asymptote#191] opened 2020-11-21 19:29 UTC
The example below, which compiles and runs in the web version, has 3 translucent squares in the `XY`, `YZ`, and `XZ` planes where the coordinates are bounded between -.25 and 1.25, so they overlap at `O`.

It renders correctly when the opacity, `op` is set to 1, but with values less that that (0.9 as below, or 0.5, for example), there are a few issues:

1. The green plane appears to stay in front of the "blue" plane, and the red plane stays in front of both. This happens independent of drawing order, as far as I can tell.

2. There are some triangular drawing artifacts near `O`. They become highly noticeable as you rotate the figure and they blip around.

3. The color of the "blue" plane is very different from the other two, but I see now that this seems to be an artifact of the lighting, so perhaps not a bug. When you tilt up, the back of the red plane is very dark, which doesn't look natural to me. But if I understand more about lighting I may learn to correct this.

Thank you, this is an amazing piece of software and I can see how much work you all have put into it!

PS this is related to a [question I posed in the forum](https://sourceforge.net/p/asymptote/discussion/409349/thread/d934b0ace3/).

```
settings.render = 16;
import three; 
size(12cm,0);
currentprojection = orthographic((5,4,1.5));

real op = 0.9;

path3 pYZ=plane(O=(0,-.25,-.25),1.5Z,1.5Y);
label("$x=0$",(0,1,1));

path3 pXZ=plane(O=(-.25,0,-.25),1.5X,1.5Z);
label("$y=0$",(1,0,1));

path3 pXY=plane(O=(-.25,-.25,0),1.5X,1.5Y);
label(project("$z=0$",Y,Z),(1,1,0));


draw(surface(pXY), red+opacity(op));
draw(surface(pXZ), green+opacity(op));
draw(surface(pYZ), blue+opacity(op));

dot(O,L="O");
dot(X,L="X");
dot(Y,L="Y");
dot(Z,L="Z");
```

**Comment by johncbowman** [comment] 2020-11-21 19:59
Duplicate of https://github.com/vectorgraphics/asymptote/issues/35

**Closed by johncbowman** 2020-11-21 19:59 UTC
