### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by radiuszero** [vectorgraphics/asymptote#254] opened 2021-06-25 20:24 UTC
Hello, I am using Asymptote 2.70 and Ghostscript 9.53.3 on MacOS Big Sur 11.4. The opacity parameter used to work before, but I just upgraded to Asymptote 2.70 yesterday and now it does not work anymore. Here is a minimal working example.
```asymptote
\documentclass{minimal}
\usepackage{asymptote}
\begin{document}
\begin{asy}
    path c = circle((0,0),1cm);
    fill(c, opacity(0.3));
\end{asy}
\end{document}
```

Compiling then gives

```if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="example-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

path c = circle((0,0),1cm);
fill(c, opacity(0.3));
```

Here is what I get when compiling with `asy -f pdf -vv example-1.asy`.

```Using configuration directory /Users/kyawshinthant/.asy
Loading config.asy from /Users/kyawshinthant/.asy/config.asy
Using history /Users/kyawshinthant/.asy/history
Welcome to Asymptote version 2.70
cd /Users/kyawshinthant/webProjects/Tutorial/opacityTesting
Processing example-1
Loading plain from /usr/local/share/asymptote/plain.asy
Including plain_constants from /usr/local/share/asymptote/plain_constants.asy
Loading version from /usr/local/share/asymptote/version.asy
Including plain_strings from /usr/local/share/asymptote/plain_strings.asy
Including plain_pens from /usr/local/share/asymptote/plain_pens.asy
Including plain_paths from /usr/local/share/asymptote/plain_paths.asy
Including plain_filldraw from /usr/local/share/asymptote/plain_filldraw.asy
Including plain_margins from /usr/local/share/asymptote/plain_margins.asy
Including plain_picture from /usr/local/share/asymptote/plain_picture.asy
Loading plain_scaling from /usr/local/share/asymptote/plain_scaling.asy
Loading simplex from /usr/local/share/asymptote/simplex.asy
Loading plain_bounds from /usr/local/share/asymptote/plain_bounds.asy
Including plain_scaling from /usr/local/share/asymptote/plain_scaling.asy
Including plain_prethree from /usr/local/share/asymptote/plain_prethree.asy
Including plain_Label from /usr/local/share/asymptote/plain_Label.asy
Including plain_arcs from /usr/local/share/asymptote/plain_arcs.asy
Including plain_boxes from /usr/local/share/asymptote/plain_boxes.asy
Including plain_shipout from /usr/local/share/asymptote/plain_shipout.asy
Including plain_markers from /usr/local/share/asymptote/plain_markers.asy
Including plain_arrows from /usr/local/share/asymptote/plain_arrows.asy
Including plain_debugger from /usr/local/share/asymptote/plain_debugger.asy
Loading example-1.asy from example-1.asy
/usr/local/bin/gs -q -dNOPAUSE -dBATCH -P -dSAFER -dALLOWPSTRANSPARENCY -sDEVICE=pdfwrite -dEPSCrop -dSubsetFonts=true -dEmbedAllFonts=true -dMaxSubsetPct=100 -dEncodeColorImages=true -dEncodeGrayImages=true -dCompatibilityLevel=1.4 -dAutoRotatePages=/None -g612x792 -dDEVICEWIDTHPOINTS=56.6929 -dDEVICEHEIGHTPOINTS=56.6929 -sOutputFile=example-1.pdf -c .setsafe -f example-1_.eps
Wrote example-1.pdf
```

Even when I changed `settings.outformat="pdf"` in the `example-1.asy` file, it only gives a black circle. What could be going wrong here? This is my first time asking, so sorry if this is a dumb question :( I am very new to Asymptote.

**Comment by johncbowman** [comment] 2021-06-25 20:35
Duplicate of https://github.com/vectorgraphics/asymptote/issues/245
The fix is in git and will be in the upcoming 2.71 release.

**Closed by johncbowman** 2021-06-25 20:35 UTC
