### ISSUE TITLE
Random build failures in parallel build (-jN)

### ISSUE THREAD

**Issue by yurivict** [vectorgraphics/asymptote#331] opened 2022-07-27 17:09 UTC
I noticed that the FreeBSD port fails spuriously when built with -j8.

There is some problem with dependencies.

**Comment by johncbowman** [comment] 2022-07-27 18:40
Does it happen when you configure with --disable-lsp?

**Comment by yurivict** [comment] 2022-07-27 18:43
It doesn't happen with ```--disable-lsp```.
I just updated the FreeBSD port and added this argument.

Thanks for your help!

**Comment by yurivict** [comment] 2022-07-27 18:44
Sorry, this bug is about -jN.

No, -jN still breaks the build.

**Comment by yurivict** [comment] 2022-07-27 18:45
To be precise: Boost issues are gone with ```--disable-lsp```, but the -jN issue is still there.

**Comment by johncbowman** [comment] 2022-08-06 20:26
I can't reproduce this issue. If you can isolate the problem, a pull request would be welcome.

**Comment by johncbowman** [comment] 2022-11-13 07:16
Can someone check if parallel builds now work properly with the latest git version?

**Comment by johncbowman** [comment] 2023-01-22 05:56
The makefile dependency issues should be fixed in commit 430c7a661c060568720f6d65e611a2087ea1dde6

**Closed by johncbowman** 2023-01-22 05:56 UTC
