### ISSUE TITLE
Three Module Failing

### ISSUE THREAD

**Issue by alpenwasser** [vectorgraphics/asymptote#52] opened 2017-12-28 11:47 UTC
Hey there,

I'm having some trouble with the 3D content (the `three` module and `graph3d`, specifically) and as best as I can tell, the error does not seem to be located between keyboard and chair (apologies if so). Specifically,
```
size(5cm);
import three;
draw(unitsphere);
```

gets me into trouble. When I create a file with the above content and run `asy` on it, I get the following output on my terminal, and no output file is produced:
```
/usr/share/asymptote/three.asy: 2905.13: runtime: ⏎ 
```

Asymptote's exit status is `0`. Running with `-keep` and/or `-keepaux` does not yield any additional files either; the only file is and remains the `.asy` file itself. Line 2905 in `three.asy` is the start of the `shipout3` routine.

Running the above commands in an _interactive_ asymptote session results in an error in `plain.asy` instead, but again on a line related to `shipout()`, if I'm not misinterpreting the results:
```
/usr/share/asymptote/plain.asy: 50.39: Singular matrix
> terminate called after throwing an instance of 'handled_error'
fish: “asy” terminated by signal SIGABRT (Abort)
```

After that, I'm dropped out of Asymptote into my shell again (fish, in this case). When running in Bash, I get an `Aborted (core dumped)` error message instead. Exit status of Asymptote is `134`.

-----------------

I'm running Arch Linux (4.9.70-1-lts kernel) and have tried the Asymptote version from the official repos (2.41-2), the AUR package (which pulls from github), and compiling and installing the master branch from github manually (just to be on the safe side). All three attempts have had the same result.

I have come across this thread in my search too (as well as some older issues mentioning segfaults, none of which I have been able to use to solve my problem yet): https://sourceforge.net/p/asymptote/discussion/409349/thread/6d0a0979/

Based on that, I compiled a checkout of the current `master` branch from github without `sigsegv` as the user in this thread did, but unlike for them, this did not change anything for me (though the user who said this solved their issue is not the OP of that thread).

The example code posted by OP in that thread results in the same behavior on my machine as my own minimal example above. It errors out when calling the `draw` command in the example, on line 2905 in `three.asy` when trying to compile the drawing as a file and on line 50 of `plain.asy` when running the commands interactively.

-----------------

Other than that, Asymptote has been working splendidly. I have had no issues with anything two-dimensional.

If you need any more information, let me know.

**Comment by alpenwasser** [comment] 2017-12-28 12:28
Small update: I fiddled around some more, and running Asymptote with the `render=0` option does yield an output file:
```
asy -render=0 myfile
```
Of course, in the case of the `unitsphere`, this produces just a black, filled circle, which isn't exactly the point, but it compiles at least, and this might at least be an acceptable workaround for other cases (Brett's 3d plot from the sourceforge thread looks pretty okay with `-render=0` on my machine, for example).

**Comment by johncbowman** [comment] 2018-04-06 04:38
The problem is likely in your OpenGL or freeglut libraries. What version of freeglut are you using?
Make sure they are up-to-date and or if so, try downgrading them. In UNIX we normally use 
freeglut 3.0.0 but under cygwin, 2.8.1 seems to be the latest stable version.

**Comment by Pouya-moh** [comment] 2018-07-18 14:49
I'm having the same issue. Since apt-get comes with 2.8.something of freeglut, I compiled version 3 from source and installed it in `/usr/lib/x86_64-linux-gnu/libglut.so.3.10.0`. Then I recompile asymptote with `./configure LDFLAGS=-L/usr/lib/x86_64-linux-gnu/ CFLAGS=-I/usr/include/GL/`, hoping that I have linked against correct version.

I still have exactly the same error, except this time it takes longer until it aborts. I have this issue with master.

**Comment by johncbowman** [comment] 2019-01-15 15:14
These issues are probably fixed with the latest git version, particularly commit  aa08fb34573824b7fa939cfaeddce802d8990e03 (which disabled offscreen rendering).
We also moved over to a GLSL shader and removed dependence on the deprecated GLU library.

**Closed by johncbowman** 2019-01-15 15:14 UTC
