### ISSUE TITLE
Arrow heads do not honor normal in vector 3D

### ISSUE THREAD

**Issue by nojhan** [vectorgraphics/asymptote#79] opened 2019-01-03 15:47 UTC
When rendering arrow heads with the `normal` parameter within 3D scenes in vector format, the heads are not projected on the indicated plane.

Minimal example below, on left produced with `settings.render = 0;`, on right with `settings.render = 8;`:
![bug_arrow_normal_vector-raster](https://user-images.githubusercontent.com/285009/50646505-8d23c500-0f76-11e9-80e4-886a5b6773e6.png)

```
settings.prc = false;
settings.render = 0; /* 0 = Vector graphics in 3D, 8= raster, 8ppp */

import three;
size(5cm);

draw(O--X, red,
    arrow=Arrow3(HookHead2(normal=Y)));

draw(O--Y, green,
    arrow=Arrow3(HookHead2(normal=Z)));

draw(O--Z, blue,
    arrow=Arrow3(HookHead2(normal=X)));
```

Asymptote 2.41-4 on Ubuntu 18.04 bionic.

**Comment by johncbowman** [comment] 2019-01-03 19:05
Duplicate of #46.

**Closed by johncbowman** 2019-01-03 19:05 UTC
